### ISSUE TITLE
rendering questions

### ISSUE THREAD

**Issue by Tycho-Xue** [allenai/objaverse-rendering#2]
Hi @mattdeitke , thanks for the rendering script! I used the engine of "CYCLES", but I found that the rendered images are quite noisy, not sure if I need to adjust the parameters. for example, it's not uncommon that the rendered images are over-exposure. the left is the rendered images, the right side is the model itself (looked up from your website, f13fa238c81c4648bd86c6378f8cf835).
![image](https://user-images.githubusercontent.com/31913279/218364527-0d356621-e454-441c-98c6-d1a84bb68f45.png)
![image](https://user-images.githubusercontent.com/31913279/218364617-045de30f-9bf5-46f6-a2fa-b7a2df16d5c4.png)

**Comment by Tycho-Xue** [comment]
I also noticed that sometimes the rendered images might be cropped or display a zig-zag pattern. I was wondering if you could provide some insights into how the parameters for rendering are determined and if you have any recommendations for tweaking them for a more generalized and better results. Thanks in advance!

**Comment by mattdeitke** [comment]
Hi @Tycho-Xue, I've now fixed this issue. Please pull the updates from the latest commit. You should get the following renders now for this object:

![000](https://user-images.githubusercontent.com/28768645/220233148-dfdd1aee-533b-4b0c-a5d3-4ba39d56ba6a.png)
![001](https://user-images.githubusercontent.com/28768645/220233153-a9132c40-3011-4544-bba4-003336e3612f.png)
![002](https://user-images.githubusercontent.com/28768645/220233156-fc6d5a0c-a1ec-4356-a27a-c9f645324207.png)
![003](https://user-images.githubusercontent.com/28768645/220233157-422094cb-6b27-4efa-beb9-2f12a9ec5c52.png)
![004](https://user-images.githubusercontent.com/28768645/220233160-03fbff6f-ecce-421b-8713-bf6dcd6f6572.png)
![005](https://user-images.githubusercontent.com/28768645/220233162-813110d0-dde4-4637-84af-a1d6d760fa20.png)
![006](https://user-images.githubusercontent.com/28768645/220233165-021e256f-63b1-4a1a-a574-1bcf10d38e86.png)
![007](https://user-images.githubusercontent.com/28768645/220233167-8f2b71f1-f574-483b-94f4-088cb26c508e.png)
![008](https://user-images.githubusercontent.com/28768645/220233168-934c9b90-b249-4a9b-b011-012683783e00.png)
![009](https://user-images.githubusercontent.com/28768645/220233170-15766f37-0ae7-4c68-b98b-c279caf879d3.png)
![010](https://user-images.githubusercontent.com/28768645/220233171-b7966954-16ec-46ad-bcd1-304a43b60d63.png)
![011](https://user-images.githubusercontent.com/28768645/220233173-f4535c50-5c77-43e4-9228-df7ae04a0f13.png)

**Comment by hayoung-jeremy** [comment]
Hi @mattdeitke , I'm currently trying running training code from [OpenLRM](https://github.com/3DTopia/OpenLRM).
They use Objaverse Rendering dataset for training.
So I'm trying to properly prepare the dataset.
However, I'm so new to AI, not sure how to prepare the data mentioned [here](https://github.com/3DTopia/OpenLRM/issues/26#issuecomment-2011337658).
I've successfully run the distributed rendering command mentioned in the README.md, and createad images :
```bash
python3 scripts/distributed.py \
  --num_gpus <NUM_GPUs> \
  --workers_per_gpu <WORKERS_PER_GPU> \
  --input_models_path <INPUT_MODELS_PATH>
```
But there is no `pose`, nor `intrinsics.npy` at all.
How can I prepare them?
It would be great if you could help me out.
Thank you for your great work!

**Comment by Piggy-ch** [comment]
> Hi @mattdeitke , I'm currently trying running training code from [OpenLRM](https://github.com/3DTopia/OpenLRM). They use Objaverse Rendering dataset for training. So I'm trying to properly prepare the dataset. However, I'm so new to AI, not sure how to prepare the data mentioned [here](https://github.com/3DTopia/OpenLRM/issues/26#issuecomment-2011337658). I've successfully run the distributed rendering command mentioned in the README.md, and createad images :
> 
> ```shell
> python3 scripts/distributed.py \
>   --num_gpus <NUM_GPUs> \
>   --workers_per_gpu <WORKERS_PER_GPU> \
>   --input_models_path <INPUT_MODELS_PATH>
> ```
> 
> But there is no `pose`, nor `intrinsics.npy` at all. How can I prepare them? It would be great if you could help me out. Thank you for your great work!

May you will generate `pose` manually.
In the "save_images" method, add the following code:

```
# save the c2w matrix
c2w_matrix = np.array(cam.matrix_world)
m_output_dir = os.path.join(args.output_dir, object_uid,'pose')
os.makedirs(m_output_dir, exist_ok=True)
with open(os.path.join(args.output_dir, object_uid,'pose', f"{i:03d}.txt"), 'w') as f:
    np.savetxt(f, c2w_matrix, fmt='%f')
```
